<?php


 /**
  *
  */
 class Idioma extends Conn
 {


      function __construct()
      {
        $this->conn = new Conn;
        $this->pdo  = $this->conn->pdo();
      }


      public function idioma($idioma){

            $array_idioma['br'] = array(
              'inadimplente' => 'Inadimplentes',
              'home' => "Home",
              'whatsapi' => "WhatsAPI",
              'financeiro' => "Financeiro",
              'planos' => "Planos",
              'configuracoes' => "Configurações",
              'pagamentos' => "Assinatura",
              'suporte' => "Suporte",
              'logs' => "Logs",
              'not_bug' => "NÃO ATRAIA 'BUGS' DURANTE A NOITE",
              'desativar' => "Desativar",
              'ativar' => "Ativar",
              'dark' => "Dark",
              'sair' => "Sair",
              'vence_hoje' => "Seu painel Gestor Lite, vence hoje",
              'escolha_plano' => "Escolha um plano Gestor Lite",
              'painel_vencido' => "Painel Gestor Lite vencido, renove",
              'erro_404' => "Oops! Parece que estamos perdidos...",
              'planos_gestor' => "Planos Gestor Lite",
              'faca_upgrade' => "Faça Upgrade para usar está função.",
              'popular' => "POPULAR",
              'contratar' => "Contratar",
              'erro_suporte' => "ERRO: Entre em contato com o suporte.",
              'so_pagar' => "Ótimo, sua fatura foi gerada! Agora é só pagar",
              'seguro_pay' => "Pagamento seguro",
              'pagar' => "Pagar",
              'prestes_downgrade' => "Você está prestes a fazer um downgrade",
              'info_atencao_down' => "Leia as informações a seguir com atenção",
              'down_o' => "Ao fazer Downgrade você :",
              'down_1' => "Se você possui mais cliente do que o permitido eles serão exluidos",
              'down_2' => "Clientes serão excluidos para cumprir a cota do plano desejado",
              'down_3' => "Exemplo: Se você possui 100 clientes e o plano desejado permite 50, os outros 50 serão deletados",
              'cancelar' => "Cancelar",
              'excluir' => "Excluir",
              'cencelar ' => "Cancelar",
              'exportar_cli' => "Exportar clientes",
              'todos' => "Todos",
              'exportar' => "Exportar",
              'continuar' => "Continuar",
              'edite_seus_dados' => "Edite seus dados",
              'nome' => "Nome",
              'email' => "Email",
              'telefone' => "Telefone",
              'senha' => "Senha",
              'salvar' => "Salvar",
              'avancado' => "Avançado",
              'adicionar' => "Adicionar",
              'movimentacao' => "movimentação",
              'valor' => "Valor",
              'atual' => "Atual",
              'janeiro' => "janeiro",
              'fevereiro' => "fevereiro",
              'marco' => "março",
              'abril' => "abril",
              'maio' => "maio",
              'junho' => "junho",
              'julho' => "julho",
              'agosto' => "agosto",
              'setembro' => "setembro",
              'outubro' => "outubro",
              'novembro' => "novembro",
              'dezembro' => "dezembro",
              'mes' => "mês",
              'entrada' => "Entrada",
              'saida' => "Saída",
              'comparado' => "Comparado",
              'anterior' => "Anterior",
              'registros' => "Registros",
              'tipo' => "tipo",
              'nota' => "nota",
              'ver' => "ver",
              'data' => "data",
              'editar' => "Editar",
              'nenhuma' => "Nenhuma",
              'nenhum' => "Nenhum",
              'registrada' => "Registrada",
              'escolha_periodo' => "Escolha o periodo",
              'periodo_expor_dados_finan' => "Escolha o periodo para exportar os dados financeiros",
              'ate' => "Até",
              'em' => "em",
              'deseja_delatar' => "Deseja realmente deletar?",
              'calma_hora' => "Muita calma nesta hora !",
              'delete_movimentacao_pergunta' => "Você realmente deseja deletar está movimentação ?",
              'deletar' => "Deletar",
              'fechar' => "Fechar",
              'campos_obrigatorios' => "Todos os campos são obrigatórios",
              'gat_title' => "Gatilhos para ser usado nos templates de mensgens",
              'gatilho' => "Gatilho",
              'funcao' => "Função",
              'gat_1' => "Nome do seu cliente que está a receber",
              'gat_1' => "Primeiro nome do seu cliente que está a receber",
              'gat_1' => "Email do seu cliente que está a receber",
              'gat_1' => "Telefone do seu cliente que está a receber",
              'gat_1' => "Vencimento do seu cliente que está a receber",
              'gat_1' => "Nome do plano que seu cliente contratou [ nome do plano que estás a configurar ]",
              'gat_1' => "Valor do plano que seu cliente contratou [ valor do plano que estás a configurar ]",
              'gat_1' => "Data atual no momento do envio da mensagem",
              'mov_este_ano' => ">Movimentado este ano:",
              'mov_este_mes' => "Movimentado este mês:",
              'comparado_com' => "Comparado com",
              'list_clientes_home' => "Lista de clientes cadastrados",
              'importar' => "Importar",
              'area_cliente' => " Área do cliente",
              'adicionar_novo' => "Adicionar novo",
              'com_selecionados' => "Com selecionados",
              'clientes' => "Clientes",
              'vencimento' => "Vencimento",
              'whatsapp' => "Whatsapp",
              'plano' => "Plano",
              'nao_definido' => "Não definido",
              'faca_upgrade_alert' => "Faça upgrade",
              'registr_de_fats' => "REGISTRO DE FATURAS",
              'adicione_um_plano' => "ADICIONE UM PLANO",
              'adicione_um_email' => "ADICIONE UM EMAIL",
              'adicione_um_telefone' => "ADICIONE UM TELEFONE",
              'nenhum_cliente_cadastrado' => "Nenhum cliente cadastrado",
              'import_clis_para_gestor_lite' => "Importar Clientes para o Gestor Lite",
              'import_permitido' => "Veja <a target='_blank' href='https://user-xtream-ui-json.gestorlite.com/' >aqui <i class='fa fa-external-link' ></i> </a> como exportar do Xtream-UI",
              'somente_json' => "Somente permitido arquivo JSON",
              'veja_de_onde_exportar' => "Veja aqui de onde exportar",
              'selecionar_arquivo' => "Selecionar arquivo",
              'selecionado' => "Selecionado",
              'editar_cliente' => "Editar Cliente",
              'acess_mini_painel_cli' => "Para acessar o <b>mini painel cliente</b>",
              'add_ddi_para_o_pais' => "Adicione <b>55</b> antes do número para BR <img width=\"10\" src=\"https://siteiptv.com/cliente/img/contry/br.png\" />, ou outro DDI do pais desejado",
              'notificas_via_zap' => "Notificar via whatsapp",
              'nao_notificar_zap' => "Não notificar via Whatsapp",
              'clientes_recebera_todos_mes_aviso' => "Seu cliente todo mês receberá aviso de vencimento",
              'selecionar_plano' => "Selecionar Plano",
              'notas' => "Notas",
              'nenhum_plano_cadastrado' => "Nenhum plano cadastrado",
              'adicionar_cliente' => "Adicionar Cliente",
              'deseja_deletar_cliente' => "Você tem certeza que deseja deletar este cliente",
              'deletar_cliente' => "Deletar Cliente",
              'faturas_cliente' => "Faturas do Cliente",
              'nova_fatura' => "Nova Fatura",
              'nova_fatura_cliente' => "Nova Fatura Cliente",
              'pendente' => "Pendente",
              'pago' => "Pago",
              'rejeitado' => "Rejeitado",
              'devolvido' => "Devolvido",
              'criar' => "Criar",
              'forma' => "Forma",
              'alterar_plano' => "Alterar Plano",
              'status' => "Status",
              'analise' => "Análise",
              'cancelado' => "Cancelado",
              'mediacao' => "Mediação",
              'o_identificador_e' => "O identificador desta fatura é",
              'valor_fat_e' => "Valor desta fatura é",
              'data_fat_e' => "Data desta fatura é",
              'form_pay_fat_e' => "Forma de pagamento da fatura é",
              'status_fat_e' => "Status da fatura é",
              'nenhuma_fat_encontrada' => "Nenhuma fatura encontrada - <a href=\"cart\" >Escolha um plano</a>",
              'ta_quase_la' => "Ta quase lá",
              'pague_sua_fat' => "Pague sua fatura",
              'faca_conf_painel_cliente' => "Faça as configurações da área do cliente",
              'acessar_area_clie' => "Acessar Área do cliente",
              'novo_aviso' => "Novo aviso",
              'titulo' => "Titulo",
              'texto' => "Texto",
              'color' => "Color",
              'auto_delete' => "Auto-Delete",
              'ver_mais' => "ver mais",
              'nenhum_aviso_criado' => "Nenhum aviso criado",
              'texto_aviso' => "Texto aviso",
              'deseja_deletar_aviso' => "Deseja realmente remover este aviso ?",
              'nao_ha_volta' => "Não há como voltar atrás parceiro(a)!",
              'quer_deletar_aviso' => "Quer mesmo deletar o aviso ?",
              'editar_aviso' => "Editar aviso",
              'quando_aviso_some' => "Quando este aviso deverá sumir ?",
              'titulo_aviso' => "Titulo do aviso",
              'texto_aviso' => "Texto do aviso",
              'adicionar_aviso' => "Adicionar Aviso",
              'nome_area_cliente' => "Nome da área do cliente",
              'caminho_aera_cli' => "Caminho da área do cliente",
              'ativado' => "Ativado",
              'desativado' => "Desativado",
              'caregar_logo' => "Carregar logo",
              'nao_gerou_area_cli' => "Você ainda não gerou a área do cliente",
              'gerar_area_cli' => "Gerar Área do cliente",
              'dias' => "Dias",
              'nenhum_plano_encontrado' => "Nenhum plano encontrado",
              'editar_plano' => "Editar Plano",
              'nome_plano' => "Nome do plano",
              'valor_plano' => "Valor do plano",
              'dias_validade' => "Dias de validade",
              'adicionar_plano' => "Adicionar plano",
              'ver_gatilhos_textos' => "Ver gatilhos de textos",
              'delete_plano' => "Deletar Plano",
              'deseja_deletar_plano' => "Você tem certeza que deseja deletar este Plano ?",
              'cliente_nenhum_usa_o_plano_para_deletar' => "Certifique-se que nenhum cliente seu usa este plano, pois pode causar danos no envio das cobranças.",
              'registros_de_atividade' => "Registros de atividade",
              'mostrados_ultimos_20' => "São mostrados os <b>últimos 10 registros</b> , os mais antigos são deletados",
              'atividade' => "Atividade",
              'hora' => "Hora",
              'nenhum_registro' => "Nenhum registro no momento",
              'mostrados_ultimos_50_whats_api' => "São mantidos em nossa base de dados os <b>últimos 20 disparos de mensagens</b>. Para que não os perca faça download constantemente",
              'mensagem' => "Mensagem",
              'nenhuma_mensagem' => "Nenhuma mensagem",
              'import_cli_gestor_lite' => "Importar Clientes para o Gestor Lite",
              'digite_nome_email_ou_telefone' => "Digite um nome, email ou telefone",
              'cadastrou_cliente' => "Cadastrou um novo cliente",
              'nao_permite_cadastrar_mais' => "Seu plano não permite cadastrar  mais clientes",
              'falha_ao_cadastrar' => "Falha ao cadastrar",
              'preencha_todos_os_campos' => "Preencha todos os campos",
              'nao_autorizado' => "Não autorizado",
              'adicionado_com_sucesso' => "adicionado com sucesso!",
              'erro_ao_add_plano' => "Erro ao adicionar plano",
              'erro' => "Erro",
              'editou_o_aviso' => "Editou o aviso",
              'aviso_edite_com_sucesso' => "Aviso editado com sucesso",
              'nao_conseguimos_editar_aviso' => "Não conseguimos editar este aviso",
              'existem_campos_vazios' => "Existem campos vazios",
              'adicionou_um_aviso' => "Adicionou um aviso",
              'aviso_add_com_sucesso' => "Aviso adicionado com sucesso",
              'nao_conseguimos_adicionar_aviso' => "Não conseguimos adicionar este aviso",
              'aviso_removido' => "Aviso removido com sucesso",
              'removeu_aviso' => "Removeu o aviso",
              'nao_conseguimos_remover_aviso' => "Não conseguimos remover este aviso",
              'nao_encontramos_aviso' => "Não encontramos este aviso",
              'nenhum_cliente_encontrado_com' => "Nenhum cliente encontrado com",
              'erro_inesperado' => "Erro inesperado, entre em contato com o suporte",
              'plano_indisponivel' => "Plano indisponível",
              'plano_nao_existe_mais' => "Me parece que este plano não existe mais, entre em contato com o suporte.",
              'fatura_ja_paga_ou_n_existe' => "Me parece que está fatura ja foi paga ou não existe mais.",
              'email_ja_existe_login' => "Este email já esta em uso em nosso sistema, faça login",
              'senha_fraca' => "Senha muito fraca",
              'conta_criada_faca_login' => "Conta criada, agora faça login",
              'pre_cadastro' => "Pré cadastro",
              'conta_criada_login_efetuado' => "Conta criada, e login efetuado",
              'erro_criar_conta' => "Erro ao criar conta, entre em contato com o suporte.",
              'preencha_todos_os_campos' => "Preencha todos os campos, por gentileza",
              'cliente_n_te_pertence' => "Cliente não te pertence",
              'cliente_n_existe' => "Cliente não existe",
              'vazio' => "vazio",
              'plano_inexistente' => "Plano inexistente",
              'usuario' => "Usuário",
              'deletado' => "deletado",
              'nao_pode_deletar' => "Você não pode deletar",
              'nao_deletado' => "não deletado",
              'email_em_uso' => "Este email ja está sendo usado em nossa base de dados, tente outro",
              'dados_alterados' => "Dados alterados com sucesso",
              'ero_editar_dados' => "Erro ao alterar seus dados, entre em contato com o suporte",
              'email_esquisito' => "Que email esquisito, tente outro",
              'esqeuceu_alguns_campos' => "Acho que você esqueceu de preencher alguns campos ai",
              'erro_alterar_painel_cli' => "Erro ao alterar painel cliente",
              'painel_cli_alterado' => "Painel cliente alterado com sucesso",
              'erro_editar_plano' => "Erro ao editar plano",
              'editado_com_sucesso' => " editado com sucesso",
              'alterou_perfil' => "Alterou o perfil",
              'perfil_atualizado' => "Perfil atualizado",
              'erro_alterar_perfil' => "Erro ao alterar perfil",
              'erro_listar_clientes' => "Erro ao listar seus clientes",
              'nao_consigo_tipo_arquivo_exportar' => "Parece que este tipo de arquivo eu ainda não consigo exportar",
              'deixou_de_dizer_algo' => "Você deixou de nos dizer algo",
              'fez_download_registros_zap' => "Fez download dos registros de Whatsapp",
              'remover_fatura' => "REMOVER FATURA",
              'deletou_a_fatura' => "Deletou a fatura",
              'criou_nova_fatura_para' => "Criou uma nova fatura para",
              'fatura_criada_com_sucesso' => "Fatura criada com sucesso",
              'erro_criar_fatura' => "Erro ao criar fatura, tente mais tarde.",
              'alterou_status_fatura' => "Alterou o status da fatura",
              'para' => "para",
              'erro_ao_alterar_status' => "Erro ao alterar status",
              'alterou_movi_de' => "Alterou a movimentação de",
              'da_data_de' => "da data de",
              'alterado_com_sucesso' => "Alterado com sucesso",
              'tentou_alterar_mov_de' => "Tentou alterar a movimentação de",
              'erro_alterar_movi' => "Erro ao alterar movimentação",
              'nao_podemos_alterar_mov' => "Não pode editar uma mivimentação que não é sua",
              'deletou_movi_de' => "Deletou uma movimentação de",
              'erro_deletar_movi' => "Erro ao deletar movimentação",
              'nao_pode_deletar_movi_n_te_pertence' => "Parece que está movimentação não pertence a você, por isso não pode deletar",
              'movimentacao_n_existe_mais' => "Parece que está movimentação já não existe mais",
              'falha' => "FALHA",
              'importado' => "IMPORTADO",
              'limit_cli_atingido' => "Limite do plano atingido, faça upgrade",
              'cliente_com_mesmo_email' => "Um cliente foi encontrado com o mesmo email",
              'formato_n_permitido' => "FORMATO DE ARQUIVO NÃO PERMITIDO, USE UM",
              'nao_foi_possivel_logar' => "Não foi possivel efetuar login no momento, tente mais tarde",
              'email_senha_incorretos' => "Email ou senha incorretos",
              'nao_pode_usar_area_cli' => "Você ão pode usar a área de cliente",
              'erro_logar' => "Erro ao efetuar login",
              'efetuou_login' => "Efetuou login",
              'area_cli_criada_com_sucesso' => "Área do cliente criada com sucesso",
              'aconteceu_erro_entre_em_contato_suporte' => "Aconteceu algum erro, entre em contato com o suporte",
              'upgrade_user_funcao' => "Faça upgrade para usar está função",
              'parece_q_n_e_usuario' => "Parece que você não é usuario",
              'add_movi_financeiro' => "Adicionou uma movimentação no financeiro",
              'movi_add_sucesso' => "Movimentação adicionada com sucesso",
              'erro_add_movi' => "Erro ao adicionar movimentação",
              'email_ja_em_uso' => "Este email já esta em uso",
              'atualizado' => "atualizado",
              'atualizou_cliente' => "Atualizou o cliente",
              'erro_atualizar_cli' => "Erro ao atualizar cliente",
              'email_ja_cadastrado_no_gestor' => "Email ja cadastrado no gestor lite",
              'email_valido' => "Coloque um email válido",
              'fez_download_registros' => "Fez download dos registros"
            );


            return $array_idioma[$idioma];

        }


      }





?>
